apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-be
  template:
    metadata:
      labels:
        app: interview-be
    spec:
      containers:
        - name: interview-be
          image: gcr.io/$(GCP_PROJECT_ID)/interview-be:latest
          ports:
            - containerPort: 4000
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GCP_PROJECT_ID
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 4000
            initialDelaySeconds: 3
            periodSeconds: 5