apiVersion: v1
kind: Service
metadata:
  name: interview-service
spec:
  selector:
    app: interview-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
