name: CI/CD PIPELINE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Create GKE Cluster (if not exists)
      run: |
        gcloud container clusters list --zone us-central1-a | grep my-cluster || \
        gcloud container clusters create my-cluster \
          --zone us-central1-a \
          --num-nodes 2 \
          --machine-type e2-medium \
          --enable-autoscaling --min-nodes 2 --max-nodes 5 \
          --enable-ip-alias \
          --no-enable-basic-auth \
          --metadata disable-legacy-endpoints=true

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate Docker with GCR
      run: gcloud auth configure-docker gcr.io

    - name: Install GKE Auth Plugin
      run: |
          gcloud components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv ./bin/trivy /usr/local/bin/

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/interview-be:latest .

    - name: Scan Docker Image with Trivy
      run: |
        trivy image --exit-code 1 --severity HIGH,CRITICAL gcr.io/${{ secrets.GCP_PROJECT_ID }}/interview-be:latest || echo "Security vulnerabilities detected"

    - name: Run Tests
      run: |
        npm install
        npm test

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/interview-be:latest

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Deploy with Helm
      run: |
        helm upgrade --install interview-be ./helm-chart \
          --set image.repository=gcr.io/${{ secrets.GCP_PROJECT_ID }}/interview-be \
          --set image.tag=latest
